
services:
  rosetta-be:
    build: .
    volumes:
      - .:/BE
    ports:
      - "8080:8080"
    environment:
      PG_DB_URL: ${PG_DB_URL}

      EDITOR_BASE_URL: ${EDITOR_BASE_URL}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - rosetta-net

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - rosetta-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "rosetta_db"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  rosetta-net:
    driver: bridge

volumes:
  db-data:
